FROM ros:jazzy
ENV DEBIAN_FRONTEND=noninteractive

# Core system + ROS packages
RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-rosdep \
    python3-opencv \
    python3-matplotlib \
    python3-numpy \
    python3-pip \
    git \
    build-essential \
    libusb-1.0-0-dev \
    wget \
    doxygen \
    joystick \
    nano \
    ros-jazzy-joy \
    ros-jazzy-cv-bridge \
    ros-jazzy-image-transport \
    ros-jazzy-teleop-twist-joy \
    ros-jazzy-sensor-msgs \
    ros-jazzy-geometry-msgs \
    ros-jazzy-nav-msgs \
    ros-jazzy-usb-cam \
    ros-jazzy-nmea-navsat-driver \
    ros-jazzy-robot-localization \
    ros-jazzy-navigation2 \
    ros-jazzy-nav2-bringup \
    ros-jazzy-slam-toolbox \
    ros-jazzy-tf2-tools \
    ros-jazzy-gps-msgs \
    ros-jazzy-gps-tools \
    ros-jazzy-phidgets-spatial \
    ros-jazzy-sick-scan-xd \
    ros-jazzy-rviz2 \
    ros-jazzy-foxglove-bridge \
    ros-jazzy-pcl-conversions \
    ros-jazzy-pcl-ros \
    ros2-testing-apt-source \
    && apt-get update && apt-get install -y \
    ros-jazzy-depthai-ros-v3 \
    && rm -rf /var/lib/apt/lists/*

# Initialize rosdep
RUN rosdep init || true
RUN rosdep update

# DepthAI Python API
RUN pip3 install --break-system-packages depthai

# Build and install ARIA
WORKDIR /tmp
RUN git clone https://github.com/reedhedges/AriaCoda.git
WORKDIR /tmp/AriaCoda
RUN make -j$(nproc)
RUN make install

# ARIA environment variables
ENV ARIA_DIR=/usr/local/Aria
ENV LD_LIBRARY_PATH=/usr/local/lib:${ARIA_DIR}/lib:$LD_LIBRARY_PATH
ENV PATH=${ARIA_DIR}/bin:$PATH

# Build Lakibeam ROS2 driver from source
RUN git clone https://github.com/RichbeamTechnology/Lakibeam_ROS2_Driver.git /opt/lakibeam_ws/src/lakibeam1
WORKDIR /opt/lakibeam_ws
RUN . /opt/ros/jazzy/setup.sh && \
    colcon build --symlink-install
RUN echo "source /opt/lakibeam_ws/install/setup.bash" >> /root/.bashrc

# Default workspace location
WORKDIR /root/auto4508_ws

# Auto-source ROS
RUN echo "source /opt/ros/jazzy/setup.bash" >> /root/.bashrc

CMD ["bash"]